USE[master]
GO
/****** Object:  Database [QLGVHS]    Script Date: 2017-12-20 11:08:46 PM ******/
CREATE DATABASE [QLGVHS]
GO
ALTER DATABASE [QLGVHS] SET COMPATIBILITY_LEVEL = 110
GO
IF(1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC[QLGVHS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLGVHS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLGVHS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLGVHS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLGVHS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLGVHS] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLGVHS] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QLGVHS] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [QLGVHS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLGVHS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLGVHS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLGVHS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLGVHS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLGVHS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLGVHS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLGVHS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLGVHS] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QLGVHS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLGVHS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLGVHS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLGVHS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLGVHS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLGVHS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLGVHS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLGVHS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QLGVHS] SET  MULTI_USER 
GO
ALTER DATABASE [QLGVHS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLGVHS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLGVHS] SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF)
GO
ALTER DATABASE [QLGVHS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE[QLGVHS]
GO
/****** Object:  Table [dbo].[GIAOVIEN]    Script Date: 2017-12-20 11:08:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIAOVIEN](
    [ID][int] IDENTITY(1, 1) NOT NULL,
    [MAGV][nvarchar](max) NULL,
    [TEN][nvarchar](max) NULL,
    [NGAYSINH][datetime] NULL,
    [GIOITINH][int] NULL,
    [QUEQUAN][nvarchar](max) NULL,
    [DIACHI][nvarchar](max) NULL,
    [SDT][nvarchar](max) NULL,
    [CHUCVU][nvarchar](max) NULL,
    PRIMARY KEY CLUSTERED 
        (
        [ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[HOCSINH]    Script Date: 2017-12-20 11:08:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOCSINH](
    [ID][int] IDENTITY(1, 1) NOT NULL,
    [MASV][nvarchar](max) NULL,
    [TEN][nvarchar](max) NULL,
    [NGAYSINH][datetime] NULL,
    [GIOITINH][int] NULL,
    [QUEQUAN][nvarchar](max) NULL,
    [SDT][nvarchar](max) NULL,
    [LOPHOCID][int] NULL,
    PRIMARY KEY CLUSTERED 
        (
        [ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LOPHOC]    Script Date: 2017-12-20 11:08:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOPHOC](
    [ID][int] IDENTITY(1, 1) NOT NULL,
    [TEN][nvarchar](max) NULL,
    [SISO][int] NULL,
    PRIMARY KEY CLUSTERED 
        (
        [ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MONHOC]    Script Date: 2017-12-20 11:08:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MONHOC](
    [ID][int] IDENTITY(1, 1) NOT NULL,
    [TEN][nvarchar](max) NULL,
    [GHICHU][nvarchar](max) NULL,
    PRIMARY KEY CLUSTERED 
        (
        [ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PHANCONG]    Script Date: 2017-12-20 11:08:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHANCONG](
    [ID][int] IDENTITY(1, 1) NOT NULL,
    [LOPHOCID][int] NULL,
    [MONHOCID][int] NULL,
    [GIAOVIENID][int] NULL,
    PRIMARY KEY CLUSTERED 
        (
        [ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TAIKHOAN]    Script Date: 2017-12-20 11:08:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOAN](
    [ID][int] IDENTITY(1, 1) NOT NULL,
    [TEN][nvarchar](max) NULL,
    [MATKHAU][nvarchar](max) NULL,
    [QUYEN][int] NULL,
    PRIMARY KEY CLUSTERED 
        (
        [ID] ASC
        )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[GIAOVIEN] ON 

INSERT[dbo].[GIAOVIEN]([ID], [MAGV], [TEN], [NGAYSINH], [GIOITINH], [QUEQUAN], [DIACHI], [SDT], [CHUCVU]) VALUES (1, N'GV01', N'Bùi Thu Lâm', CAST(0x00006F3D0153C5A1 AS DateTime), 1, N'Hà Nội', N'Hà Nội', N'09874258921', N'Chủ nhiệm khoa')
INSERT[dbo].[GIAOVIEN]([ID], [MAGV], [TEN], [NGAYSINH], [GIOITINH], [QUEQUAN], [DIACHI], [SDT], [CHUCVU]) VALUES (2, N'GV02', N'Phan Nguyên Hải', CAST(0x00006F3D0156C2B4 AS DateTime), 1, N'Hà Tĩnh, Vĩnh Phúc, Phú Thọ', N'Hà Nội', N'09128596342', N'Chủ nhiệm bộ môn')
SET IDENTITY_INSERT [dbo].[GIAOVIEN] OFF
SET IDENTITY_INSERT [dbo].[HOCSINH] ON 

INSERT[dbo].[HOCSINH]([ID], [MASV], [TEN], [NGAYSINH], [GIOITINH], [QUEQUAN], [SDT], [LOPHOCID]) VALUES (1, N'HS01', N'Trần Tuấn Phong', CAST(0x00008A59015D469D AS DateTime), 1, N'Nam Định', N'09867452152', 1)
INSERT[dbo].[HOCSINH]([ID], [MASV], [TEN], [NGAYSINH], [GIOITINH], [QUEQUAN], [SDT], [LOPHOCID]) VALUES (2, N'HS02', N'Nguyễn Nam Anh', CAST(0x00008A59015D6C71 AS DateTime), 0, N'Hà Tĩnh', N'0665992522', 2)
INSERT[dbo].[HOCSINH]([ID], [MASV], [TEN], [NGAYSINH], [GIOITINH], [QUEQUAN], [SDT], [LOPHOCID]) VALUES (4, N'HS03', N'VŨ ĐÌNH ĐẠT', CAST(0x00008A5901696039 AS DateTime), 1, N'HƯNG YÊN', N'112154545', 2)
SET IDENTITY_INSERT [dbo].[HOCSINH] OFF
SET IDENTITY_INSERT [dbo].[LOPHOC] ON 

INSERT[dbo].[LOPHOC]([ID], [TEN], [SISO]) VALUES (1, N'Lớp 10A1', 1)
INSERT[dbo].[LOPHOC]([ID], [TEN], [SISO]) VALUES (2, N'Lớp 10A3', 2)
SET IDENTITY_INSERT [dbo].[LOPHOC] OFF
SET IDENTITY_INSERT [dbo].[MONHOC] ON 

INSERT[dbo].[MONHOC]([ID], [TEN], [GHICHU]) VALUES (1, N'Toán', N'')
INSERT[dbo].[MONHOC]([ID], [TEN], [GHICHU]) VALUES (3, N'Văn', N'')
INSERT[dbo].[MONHOC]([ID], [TEN], [GHICHU]) VALUES (4, N'Anh', N'')
SET IDENTITY_INSERT [dbo].[MONHOC] OFF
SET IDENTITY_INSERT [dbo].[PHANCONG] ON 

INSERT[dbo].[PHANCONG]([ID], [LOPHOCID], [MONHOCID], [GIAOVIENID]) VALUES (1, 1, 1, 1)
INSERT[dbo].[PHANCONG]([ID], [LOPHOCID], [MONHOCID], [GIAOVIENID]) VALUES (3, 2, 1, 2)
SET IDENTITY_INSERT [dbo].[PHANCONG] OFF
SET IDENTITY_INSERT [dbo].[TAIKHOAN] ON 

INSERT[dbo].[TAIKHOAN]([ID], [TEN], [MATKHAU], [QUYEN]) VALUES (1, N'admin', N'1', 1)
INSERT[dbo].[TAIKHOAN]([ID], [TEN], [MATKHAU], [QUYEN]) VALUES (2, N'user', N'123', 0)
INSERT[dbo].[TAIKHOAN]([ID], [TEN], [MATKHAU], [QUYEN]) VALUES (4, N'user2', N'1', 0)
SET IDENTITY_INSERT [dbo].[TAIKHOAN] OFF
ALTER TABLE [dbo].[HOCSINH]  WITH CHECK ADD FOREIGN KEY([LOPHOCID])
REFERENCES[dbo].[LOPHOC]([ID])
GO
ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD FOREIGN KEY([GIAOVIENID])
REFERENCES[dbo].[GIAOVIEN]([ID])
GO
ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD FOREIGN KEY([LOPHOCID])
REFERENCES[dbo].[LOPHOC]([ID])
GO
ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD FOREIGN KEY([MONHOCID])
REFERENCES[dbo].[MONHOC]([ID])
GO
USE[master]
GO
ALTER DATABASE [QLGVHS] SET  READ_WRITE 
GO
